### ISSUE TITLE
s11_TreeViewCustomCell のツリーを畳むと例外が発生する。

### ISSUE THREAD

**Issue by mikoto2000** [mikoto2000/MiscellaneousStudy#1]
ウィンドウが表示された直後に 'id4, displayName4' を畳んだ時に書き例外が発生した。

```console
javafx.fxml.LoadException: Root value already specified.
file:/C:/Users/mikoto/project/MiscellaneousStudy/java/JavaFX/build/libs/JavaFX.jar!/MyTreeViewCell.fxml
file:/C:/Users/mikoto/project/MiscellaneousStudy/java/JavaFX/build/libs/JavaFX.jar!/MyTreeViewCell.fxml

        at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2597)
        at javafx.fxml.FXMLLoader.createElement(FXMLLoader.java:2755)
        at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2704)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
        at jp.dip.oyasirazu.study.javafx.MyTreeViewCell.updateItem(MyTreeViewCell.java:29)
        at jp.dip.oyasirazu.study.javafx.MyTreeViewCell.updateItem(MyTreeViewCell.java:14)
        at javafx.scene.control.TreeCell.updateItem(TreeCell.java:516)
        at javafx.scene.control.TreeCell.indexChanged(TreeCell.java:474)
        at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
        at com.sun.javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1957)
        at com.sun.javafx.scene.control.skin.VirtualFlow.addLeadingCells(VirtualFlow.java:1246)
        at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1194)
        at javafx.scene.Parent.layout(Parent.java:1087)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Scene.doLayoutPass(Scene.java:552)
        at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        at java.lang.Thread.run(Thread.java:745)
erroe!
javafx.fxml.LoadException: Root value already specified.
file:/C:/Users/mikoto/project/MiscellaneousStudy/java/JavaFX/build/libs/JavaFX.jar!/MyTreeViewCell.fxml
file:/C:/Users/mikoto/project/MiscellaneousStudy/java/JavaFX/build/libs/JavaFX.jar!/MyTreeViewCell.fxml

        at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2597)
        at javafx.fxml.FXMLLoader.createElement(FXMLLoader.java:2755)
        at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2704)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
        at jp.dip.oyasirazu.study.javafx.MyTreeViewCell.updateItem(MyTreeViewCell.java:29)
        at jp.dip.oyasirazu.study.javafx.MyTreeViewCell.updateItem(MyTreeViewCell.java:14)
        at javafx.scene.control.TreeCell.updateItem(TreeCell.java:516)
        at javafx.scene.control.TreeCell.indexChanged(TreeCell.java:474)
        at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
        at com.sun.javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1957)
        at com.sun.javafx.scene.control.skin.VirtualFlow.addTrailingCells(VirtualFlow.java:1344)
        at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1197)
        at javafx.scene.Parent.layout(Parent.java:1087)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Scene.doLayoutPass(Scene.java:552)
        at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        at java.lang.Thread.run(Thread.java:745)
erroe!
javafx.fxml.LoadException: Root value already specified.
file:/C:/Users/mikoto/project/MiscellaneousStudy/java/JavaFX/build/libs/JavaFX.jar!/MyTreeViewCell.fxml
file:/C:/Users/mikoto/project/MiscellaneousStudy/java/JavaFX/build/libs/JavaFX.jar!/MyTreeViewCell.fxml

        at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2597)
        at javafx.fxml.FXMLLoader.createElement(FXMLLoader.java:2755)
        at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2704)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
        at jp.dip.oyasirazu.study.javafx.MyTreeViewCell.updateItem(MyTreeViewCell.java:29)
        at jp.dip.oyasirazu.study.javafx.MyTreeViewCell.updateItem(MyTreeViewCell.java:14)
        at javafx.scene.control.TreeCell.updateItem(TreeCell.java:516)
        at javafx.scene.control.TreeCell.indexChanged(TreeCell.java:474)
        at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
        at com.sun.javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1957)
        at com.sun.javafx.scene.control.skin.VirtualFlow.addTrailingCells(VirtualFlow.java:1344)
        at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1197)
        at javafx.scene.Parent.layout(Parent.java:1087)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Scene.doLayoutPass(Scene.java:552)
        at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        at java.lang.Thread.run(Thread.java:745)
erroe!
javafx.fxml.LoadException: Root value already specified.
file:/C:/Users/mikoto/project/MiscellaneousStudy/java/JavaFX/build/libs/JavaFX.jar!/MyTreeViewCell.fxml
file:/C:/Users/mikoto/project/MiscellaneousStudy/java/JavaFX/build/libs/JavaFX.jar!/MyTreeViewCell.fxml

        at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2597)
        at javafx.fxml.FXMLLoader.createElement(FXMLLoader.java:2755)
        at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2704)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
        at jp.dip.oyasirazu.study.javafx.MyTreeViewCell.updateItem(MyTreeViewCell.java:29)
        at jp.dip.oyasirazu.study.javafx.MyTreeViewCell.updateItem(MyTreeViewCell.java:14)
        at javafx.scene.control.TreeCell.updateItem(TreeCell.java:516)
        at javafx.scene.control.TreeCell.indexChanged(TreeCell.java:474)
        at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
        at com.sun.javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1957)
        at com.sun.javafx.scene.control.skin.VirtualFlow.addTrailingCells(VirtualFlow.java:1344)
        at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1197)
        at javafx.scene.Parent.layout(Parent.java:1087)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Scene.doLayoutPass(Scene.java:552)
        at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        at java.lang.Thread.run(Thread.java:745)
erroe!
javafx.fxml.LoadException: Root value already specified.
file:/C:/Users/mikoto/project/MiscellaneousStudy/java/JavaFX/build/libs/JavaFX.jar!/MyTreeViewCell.fxml
file:/C:/Users/mikoto/project/MiscellaneousStudy/java/JavaFX/build/libs/JavaFX.jar!/MyTreeViewCell.fxml

        at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2597)
        at javafx.fxml.FXMLLoader.createElement(FXMLLoader.java:2755)
        at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2704)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
        at jp.dip.oyasirazu.study.javafx.MyTreeViewCell.updateItem(MyTreeViewCell.java:29)
        at jp.dip.oyasirazu.study.javafx.MyTreeViewCell.updateItem(MyTreeViewCell.java:14)
        at javafx.scene.control.TreeCell.updateItem(TreeCell.java:516)
        at javafx.scene.control.TreeCell.indexChanged(TreeCell.java:474)
        at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
        at com.sun.javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1957)
        at com.sun.javafx.scene.control.skin.VirtualFlow.addTrailingCells(VirtualFlow.java:1344)
        at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1197)
        at javafx.scene.Parent.layout(Parent.java:1087)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Scene.doLayoutPass(Scene.java:552)
        at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        at java.lang.Thread.run(Thread.java:745)
erroe!
```

**Comment by mikoto2000** [comment]
aaaaa
